export const categories = {
  income: [
    {
      type: "income",
      description: "Deposit",
      icon: "fas fa-align-justify",
      name: "incomeCategory",
      value: "deposit",
      color: "",
    },
    {
      type: "income",
      description: "Salary",
      icon: "fas fa-align-justify",
      name: "incomeCategory",
      value: "salary",
      color: "",
    },
    {
      type: "income",
      description: "Savings",
      icon: "fas fa-align-justify",
      name: "incomeCategory",
      value: "savings",
      color: "",
    },
  ],
  expense: [
    {
      description: "Auto",
      type: "expense",
      icon: "fas fa-align-justify",
      name: "expenseCategory",
      value: "auto",
      color: "",
    },
    {
      description: "Bills",
      type: "expense",
      icon: "fas fa-align-justify",
      name: "expenseCategory",
      value: "bills",
      color: "",
    },
    {
      description: "clothes",
      type: "expense",
      icon: "fas fa-align-justify",
      name: "expenseCategory",
      value: "clothes",
      color: "",
    },
    {
      description: "Entertainment",
      type: "expense",
      icon: "fas fa-align-justify",
      name: "expenseCategory",
      value: "entertainment",
      color: "",
    },
    {
      description: "Food",
      type: "expense",
      icon: "fas fa-align-justify",
      name: "expenseCategory",
      value: "food",
      color: "",
    },
    {
      description: "Fuel",
      type: "expense",
      icon: "fas fa-align-justify",
      name: "expenseCategory",
      value: "fuel",
      color: "",
    },
    {
      description: "General",
      type: "expense",
      icon: "fas fa-align-justify",
      name: "expenseCategory",
      value: "general",
      color: "",
    },
    {
      description: "Gifts",
      type: "expense",
      icon: "fas fa-align-justify",
      name: "expenseCategory",
      value: "gifts",
      color: "",
    },
    {
      description: "Health",
      type: "expense",
      icon: "fas fa-align-justify",
      name: "expenseCategory",
      value: "health",
      color: "",
    },
    {
      description: "Holidays",
      type: "expense",
      icon: "fas fa-align-justify",
      name: "expenseCategory",
      value: "holidays",
      color: "",
    },
    {
      description: "Home",
      type: "expense",
      icon: "fas fa-align-justify",
      name: "expenseCategory",
      value: "home",
      color: "",
    },
    {
      description: "Kids",
      type: "expense",
      icon: "fas fa-align-justify",
      name: "expenseCategory",
      value: "kids",
      color: "",
    },
    {
      description: "Shopping",
      type: "expense",
      icon: "fas fa-align-justify",
      name: "expenseCategory",
      value: "shopping",
      color: "",
    },
    {
      description: "Sports",
      type: "expense",
      icon: "fas fa-align-justify",
      name: "expenseCategory",
      value: "sports",
      color: "",
    },
  ],
};
